### ISSUE TITLE
Repository Not Found

### ISSUE THREAD

**Issue by juliusgambe** [tryWabbit/Layout-Helper#16] opened 2021-04-29 04:42 UTC
I cannot install Layout Helper via Cocoapods. 

`fatal: repository 'https://github.com/tryWabbit/Layout-Helper-Pod.git/' not found`

**Comment by tryWabbit** [comment] 2021-06-24 04:15
<img width="232" alt="Screenshot 2021-06-24 at 9 44 24 AM" src="https://user-images.githubusercontent.com/20557360/123201684-cb0f5d80-d4d0-11eb-85b1-93e0cf979c89.png">

Thank you for using the library @juliusgambe , I just checked and it's working fine for me. 

Can you provide more detail?

Thanks

**Comment by tryWabbit** [comment] 2021-06-30 02:57
The issue is invalid and closing it because there are no feedbacks from the user.

**Closed as completed by tryWabbit** 2021-06-30 02:57 UTC
Labels: invalid
